# Generated by Django 4.2 on 2023-08-25 05:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('P_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('p_description', models.TextField(blank=True)),
                ('P_image', models.ImageField(upload_to='product_images')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('photo', models.ImageField(upload_to='profile_images')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
